name: Run bot

on:
  schedule:
    # 2時間ごとに処理実行
    - cron: "0 */2 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 1
    env:
      CONSUMER_KEY: ${{ secrets.AVBOT_CONSUMER_KEY }}
      CONSUMER_SECRET: ${{ secrets.AVBOT_CONSUMER_SECRET }}
      ACCESS_TOKEN_KEY: ${{ secrets.AVBOT_ACCESS_TOKEN_KEY }}
      ACCESS_TOKEN_SECRET: ${{ secrets.AVBOT_ACCESS_TOKEN_SECRET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: kakudenbuzo/avbot
          path: avbot
          token: ${{ secrets.GH_PAT }}
      
      - name: Package install
        run: npm ci
        working-directory: avbot

      - name: Build
        run: npm run build
        working-directory: avbot
        
      - name: Run bot
        run: node lib/index.js
        working-directory: avbot
